version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: employee-postgres
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nodeapp:
    build: ./backend
    container_name: employee-nodeapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: employeedb
      DB_PORT: 5432

volumes:
  pgdata:

